port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'

proxies:
  - name: "example-proxy"
    type: vmess
    server: example.com
    port: 443
    uuid: "YOUR_UUID"
    alterId: 64
    cipher: auto
    tls: true

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "example-proxy"

rules:
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
